name: motto_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  google_fonts: ^6.2.1 
  shared_preferences: ^2.5.3
  carousel_slider: ^5.1.1
  standard_searchbar: ^2.1.1
  lottie: ^3.1.2
  dropdown_button2: ^2.3.9
  animated_text_kit: ^4.2.2
  animated_custom_dropdown: ^3.1.1
  floating_snackbar: ^1.0.5
  confirmation_success: ^0.0.2
  fade_scroll_app_bar: ^0.0.7
  custom_animation_appbar: ^2.0.0
  apptomate_custom_silver_appbar: ^0.0.1
  scrollable_list_tabview: ^0.2.0-nullsafety
  image_picker: ^1.2.0
  stylish_bottom_bar: ^1.1.1
  google_maps_flutter: ^2.13.1
  cloud_firestore: ^6.0.2
  uuid: ^4.5.1
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img1.png
    - assets/img2.png
    - assets/img3.png
    - assets/img4.png
    - assets/img5.png
    - assets/animated_img.png
    - assets/CardImages/fuji1.jpg
    - assets/CardImages/fuji2.jpg
    - assets/CardImages/fuji3.jpg
    - assets/login.png
    - assets/logo2.png

